### PR TITLE
compress the zip file with gzip

### PR DESCRIPTION
**Pull request by aviadhaham**
was bored, obviously it's nothing
but if you want to merge :)

noticed that the different was around 3rd the size of the original zip without the gzip compression

### CODE REVIEW

**Comment by orellazri** [comment]
looks good, but zip files usually don't tend to end with `.gz` even when compressed with gzip.
update your PR so it doesn't change the file extension

**Comment by aviadhaham** [comment]
I know, but I wanted it to be clear that it's a gzipped ZIP, so I won't have to run `file myzip.zip` to check what type of compression was done.

let me know if you still want me to change.

**Comment by orellazri** [comment]
@aviadhaham I get what you’re saying, but still, having a .zip.gz file feels weird.

Also, does the new compressed file contain the actual zip inside? So you’ll have to extract twice?

Is the zip archive coming from Todoist not already compressed?

**Comment by aviadhaham** [comment]
I remember it's not compressed, from todoist.
In any case, I removed the GZ suffix change.

**Comment by orellazri** [comment]
@aviadhaham  could you check if the output archive contains another zip inside?

**Comment by aviadhaham** [comment]
there isn't, the end result is just a GZIP compressed ZIP file
So to reach the actual backed up files, you need to:
1. Decompress the file: `gzip -d <gzip_compressed_zip>`
2. unzip the zip: `unzip <decompressed_zip>`

@orellazri

**Pull request closed without merging**
